<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

if (false) {
    /**
     * This class is deprecated. Use Etcd\Compare\CompareResult instead.
     * @deprecated
     */
    class Compare_CompareResult {}
}
class_exists(Compare\CompareResult::class);
@trigger_error('Etcd\Compare_CompareResult is deprecated and will be removed in the next major release. Use Etcd\Compare\CompareResult instead', E_USER_DEPRECATED);

