<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

if (false) {
    /**
     * This class is deprecated. Use Etcd\Compare\CompareTarget instead.
     * @deprecated
     */
    class Compare_CompareTarget {}
}
class_exists(Compare\CompareTarget::class);
@trigger_error('Etcd\Compare_CompareTarget is deprecated and will be removed in the next major release. Use Etcd\Compare\CompareTarget instead', E_USER_DEPRECATED);

