<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.Compare</code>
 */
class Compare extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.Compare.CompareResult result = 1;</code>
     */
    protected $result = 0;
    /**
     * Generated from protobuf field <code>.etcdserverpb.Compare.CompareTarget target = 2;</code>
     */
    protected $target = 0;
    /**
     * key path
     *
     * Generated from protobuf field <code>bytes key = 3;</code>
     */
    protected $key = '';
    protected $target_union;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type int $target
     *     @type string $key
     *           key path
     *     @type int|string $version
     *           version of the given key
     *     @type int|string $create_revision
     *           create revision of the given key
     *     @type int|string $mod_revision
     *           last modified revision of the given key
     *     @type string $value
     *           value of the given key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.Compare.CompareResult result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.Compare.CompareResult result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Etcd\Compare\CompareResult::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.Compare.CompareTarget target = 2;</code>
     * @return int
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.Compare.CompareTarget target = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkEnum($var, \Etcd\Compare\CompareTarget::class);
        $this->target = $var;

        return $this;
    }

    /**
     * key path
     *
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * key path
     *
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * version of the given key
     *
     * Generated from protobuf field <code>int64 version = 4;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->readOneof(4);
    }

    public function hasVersion()
    {
        return $this->hasOneof(4);
    }

    /**
     * version of the given key
     *
     * Generated from protobuf field <code>int64 version = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * create revision of the given key
     *
     * Generated from protobuf field <code>int64 create_revision = 5;</code>
     * @return int|string
     */
    public function getCreateRevision()
    {
        return $this->readOneof(5);
    }

    public function hasCreateRevision()
    {
        return $this->hasOneof(5);
    }

    /**
     * create revision of the given key
     *
     * Generated from protobuf field <code>int64 create_revision = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * last modified revision of the given key
     *
     * Generated from protobuf field <code>int64 mod_revision = 6;</code>
     * @return int|string
     */
    public function getModRevision()
    {
        return $this->readOneof(6);
    }

    public function hasModRevision()
    {
        return $this->hasOneof(6);
    }

    /**
     * last modified revision of the given key
     *
     * Generated from protobuf field <code>int64 mod_revision = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setModRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * value of the given key
     *
     * Generated from protobuf field <code>bytes value = 7;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->readOneof(7);
    }

    public function hasValue()
    {
        return $this->hasOneof(7);
    }

    /**
     * value of the given key
     *
     * Generated from protobuf field <code>bytes value = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getTargetUnion()
    {
        return $this->whichOneof("target_union");
    }

}

