<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.LeaseKeepAliveResponse</code>
 */
class LeaseKeepAliveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>int64 ID = 2;</code>
     */
    protected $ID = 0;
    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     */
    protected $TTL = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type int|string $ID
     *     @type int|string $TTL
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ID = 2;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>int64 ID = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @return int|string
     */
    public function getTTL()
    {
        return $this->TTL;
    }

    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->TTL = $var;

        return $this;
    }

}

