<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.Member</code>
 */
class Member extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     */
    protected $ID = 0;
    /**
     * If the member is not started, name will be an empty string.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bool IsLeader = 3;</code>
     */
    protected $IsLeader = false;
    /**
     * Generated from protobuf field <code>repeated string peerURLs = 4;</code>
     */
    private $peerURLs;
    /**
     * If the member is not started, client_URLs will be an zero length
     * string array.
     *
     * Generated from protobuf field <code>repeated string clientURLs = 5;</code>
     */
    private $clientURLs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ID
     *     @type string $name
     *           If the member is not started, name will be an empty string.
     *     @type bool $IsLeader
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $peerURLs
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $clientURLs
     *           If the member is not started, client_URLs will be an zero length
     *           string array.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * If the member is not started, name will be an empty string.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * If the member is not started, name will be an empty string.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsLeader = 3;</code>
     * @return bool
     */
    public function getIsLeader()
    {
        return $this->IsLeader;
    }

    /**
     * Generated from protobuf field <code>bool IsLeader = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLeader($var)
    {
        GPBUtil::checkBool($var);
        $this->IsLeader = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string peerURLs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeerURLs()
    {
        return $this->peerURLs;
    }

    /**
     * Generated from protobuf field <code>repeated string peerURLs = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeerURLs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peerURLs = $arr;

        return $this;
    }

    /**
     * If the member is not started, client_URLs will be an zero length
     * string array.
     *
     * Generated from protobuf field <code>repeated string clientURLs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClientURLs()
    {
        return $this->clientURLs;
    }

    /**
     * If the member is not started, client_URLs will be an zero length
     * string array.
     *
     * Generated from protobuf field <code>repeated string clientURLs = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClientURLs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->clientURLs = $arr;

        return $this;
    }

}

