<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.MemberUpdateRequest</code>
 */
class MemberUpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     */
    protected $ID = 0;
    /**
     * Generated from protobuf field <code>repeated string peerURLs = 2;</code>
     */
    private $peerURLs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ID
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $peerURLs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string peerURLs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPeerURLs()
    {
        return $this->peerURLs;
    }

    /**
     * Generated from protobuf field <code>repeated string peerURLs = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPeerURLs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peerURLs = $arr;

        return $this;
    }

}

