<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

if (false) {
    /**
     * This class is deprecated. Use Etcd\RangeRequest\SortOrder instead.
     * @deprecated
     */
    class RangeRequest_SortOrder {}
}
class_exists(RangeRequest\SortOrder::class);
@trigger_error('Etcd\RangeRequest_SortOrder is deprecated and will be removed in the next major release. Use Etcd\RangeRequest\SortOrder instead', E_USER_DEPRECATED);

