<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

if (false) {
    /**
     * This class is deprecated. Use Etcd\RangeRequest\SortTarget instead.
     * @deprecated
     */
    class RangeRequest_SortTarget {}
}
class_exists(RangeRequest\SortTarget::class);
@trigger_error('Etcd\RangeRequest_SortTarget is deprecated and will be removed in the next major release. Use Etcd\RangeRequest\SortTarget instead', E_USER_DEPRECATED);

