<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.RangeResponse</code>
 */
class RangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>repeated .storagepb.KeyValue kvs = 2;</code>
     */
    private $kvs;
    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     */
    protected $more = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type array<\Etcd\KeyValue>|\Google\Protobuf\Internal\RepeatedField $kvs
     *     @type bool $more
     *           more indicates if there are more keys to return in the requested range.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .storagepb.KeyValue kvs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKvs()
    {
        return $this->kvs;
    }

    /**
     * Generated from protobuf field <code>repeated .storagepb.KeyValue kvs = 2;</code>
     * @param array<\Etcd\KeyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKvs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\KeyValue::class);
        $this->kvs = $arr;

        return $this;
    }

    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     * @return bool
     */
    public function getMore()
    {
        return $this->more;
    }

    /**
     * more indicates if there are more keys to return in the requested range.
     *
     * Generated from protobuf field <code>bool more = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMore($var)
    {
        GPBUtil::checkBool($var);
        $this->more = $var;

        return $this;
    }

}

