<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.RequestUnion</code>
 */
class RequestUnion extends \Google\Protobuf\Internal\Message
{
    protected $request;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\RangeRequest $request_range
     *     @type \Etcd\PutRequest $request_put
     *     @type \Etcd\DeleteRangeRequest $request_delete_range
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     * @return \Etcd\RangeRequest
     */
    public function getRequestRange()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     * @param \Etcd\RangeRequest $var
     * @return $this
     */
    public function setRequestRange($var)
    {
        GPBUtil::checkMessage($var, \Etcd\RangeRequest::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutRequest request_put = 2;</code>
     * @return \Etcd\PutRequest
     */
    public function getRequestPut()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutRequest request_put = 2;</code>
     * @param \Etcd\PutRequest $var
     * @return $this
     */
    public function setRequestPut($var)
    {
        GPBUtil::checkMessage($var, \Etcd\PutRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     * @return \Etcd\DeleteRangeRequest
     */
    public function getRequestDeleteRange()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     * @param \Etcd\DeleteRangeRequest $var
     * @return $this
     */
    public function setRequestDeleteRange($var)
    {
        GPBUtil::checkMessage($var, \Etcd\DeleteRangeRequest::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

