<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.ResponseHeader</code>
 */
class ResponseHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     */
    protected $cluster_id = 0;
    /**
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     */
    protected $member_id = 0;
    /**
     * revision of the store when the request was applied.
     *
     * Generated from protobuf field <code>int64 revision = 3;</code>
     */
    protected $revision = 0;
    /**
     * term of raft when the request was applied.
     *
     * Generated from protobuf field <code>uint64 raft_term = 4;</code>
     */
    protected $raft_term = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $cluster_id
     *     @type int|string $member_id
     *     @type int|string $revision
     *           revision of the store when the request was applied.
     *     @type int|string $raft_term
     *           term of raft when the request was applied.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     * @return int|string
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * Generated from protobuf field <code>uint64 cluster_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClusterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     * @return int|string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkUint64($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     * revision of the store when the request was applied.
     *
     * Generated from protobuf field <code>int64 revision = 3;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * revision of the store when the request was applied.
     *
     * Generated from protobuf field <code>int64 revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * term of raft when the request was applied.
     *
     * Generated from protobuf field <code>uint64 raft_term = 4;</code>
     * @return int|string
     */
    public function getRaftTerm()
    {
        return $this->raft_term;
    }

    /**
     * term of raft when the request was applied.
     *
     * Generated from protobuf field <code>uint64 raft_term = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRaftTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->raft_term = $var;

        return $this;
    }

}

