<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.ResponseUnion</code>
 */
class ResponseUnion extends \Google\Protobuf\Internal\Message
{
    protected $response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\RangeResponse $response_range
     *     @type \Etcd\PutResponse $response_put
     *     @type \Etcd\DeleteRangeResponse $response_delete_range
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     * @return \Etcd\RangeResponse
     */
    public function getResponseRange()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     * @param \Etcd\RangeResponse $var
     * @return $this
     */
    public function setResponseRange($var)
    {
        GPBUtil::checkMessage($var, \Etcd\RangeResponse::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutResponse response_put = 2;</code>
     * @return \Etcd\PutResponse
     */
    public function getResponsePut()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.PutResponse response_put = 2;</code>
     * @param \Etcd\PutResponse $var
     * @return $this
     */
    public function setResponsePut($var)
    {
        GPBUtil::checkMessage($var, \Etcd\PutResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     * @return \Etcd\DeleteRangeResponse
     */
    public function getResponseDeleteRange()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     * @param \Etcd\DeleteRangeResponse $var
     * @return $this
     */
    public function setResponseDeleteRange($var)
    {
        GPBUtil::checkMessage($var, \Etcd\DeleteRangeResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

