<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Proto/rpc.proto

namespace Etcd;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>etcdserverpb.TxnResponse</code>
 */
class TxnResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     */
    protected $succeeded = false;
    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseUnion responses = 3;</code>
     */
    private $responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Etcd\ResponseHeader $header
     *     @type bool $succeeded
     *     @type \Etcd\ResponseUnion[]|\Google\Protobuf\Internal\RepeatedField $responses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @return \Etcd\ResponseHeader
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.etcdserverpb.ResponseHeader header = 1;</code>
     * @param \Etcd\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Etcd\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     * @return bool
     */
    public function getSucceeded()
    {
        return $this->succeeded;
    }

    /**
     * Generated from protobuf field <code>bool succeeded = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSucceeded($var)
    {
        GPBUtil::checkBool($var);
        $this->succeeded = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseUnion responses = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * Generated from protobuf field <code>repeated .etcdserverpb.ResponseUnion responses = 3;</code>
     * @param \Etcd\ResponseUnion[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcd\ResponseUnion::class);
        $this->responses = $arr;

        return $this;
    }

}

